GothamCrimeProject/GothamCrime.UI/Controllers/GCCrimeReportNotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GothamCrimProject.DATA;

namespace GothamCrime.UI.Controllers
{
    [Authorize]
    public class GCCrimeReportNotesController : Controller
    {
        private GothamCrimesEntities db = new GothamCrimesEntities();
        
        //public JsonResult AddCRNote(int CRId, string note)
        //{
        //    //Grab the Crime Report
        //    GCCrimeReport cR = db.GCCrimeReports.Single(x => x.CrimeReportID == CRId);
        //    //Get the Employee
        //    GCPerson author = db.GCPersons.ToList().FirstOrDefault(x => x.PersonID == (int)Session["userID"]);

        //    if (author != null)
        //    {
        //        //Create the Note
        //        GCCrimeReportNote newNote = new GCCrimeReportNote()
        //        {
        //            CRNCrimeID = cR.CrimeReportID,
        //            CRNAuthorID = author.PersonID,
        //            CRNDate = DateTime.Now,
        //            CRNote = note
        //        };
        //        db.GCCrimeReportNotes.Add(newNote);
        //        db.SaveChanges();

        //        var data = new
        //        {
        //            CRNote = newNote.CRNote,
        //            Author = newNote.GCPerson.AliasOr,
        //            Date = string.Format("{0:D}", newNote.CRNDate)
        //        };
        //        return Json(data, JsonRequestBehavior.AllowGet);
        //    }
        //    return null;
        //}

        // GET: GCCrimeReportNotes
        public ActionResult Index()
        {
            var gCCrimeReportNotes = db.GCCrimeReportNotes.Include(g => g.GCCrimeReport).Include(g => g.GCPerson);
            return View(gCCrimeReportNotes.ToList());
        }

        // GET: GCCrimeReportNotes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCCrimeReportNote gCCrimeReportNote = db.GCCrimeReportNotes.Find(id);
            if (gCCrimeReportNote == null)
            {
                return HttpNotFound();
            }
            return View(gCCrimeReportNote);
        }

        // GET: GCCrimeReportNotes/Create
        public ActionResult Create(int id)
        {
            ViewBag.CRNCrimeID = new SelectList(db.GCCrimeReports, "CrimeReportID", "Evidence");
            ViewBag.CRNAuthorID = new SelectList(db.GCPersons, "PersonID", "PersonFName");
            //Create the Note
            //GCCrimeReportNote newNote = new GCCrimeReportNote()
            //{
            //    CRNCrimeID = id
            //};
            TempData["passid"] = id;
            return PartialView();
        }

        // POST: GCCrimeReportNotes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CrimeReportNoteID,CRNAuthorID,CRNote,CRNCrimeID,CRNDate")] GCCrimeReportNote gCCrimeReportNote)
        {
            
            if (ModelState.IsValid)
            {
                //Grab the Crime Report
                //GCCrimeReport cR = db.GCCrimeReports.Single(x => x.CrimeReportID == gCCrimeReportNote.CRNCrimeID);
                //Get the Employee
                GCPerson author = db.GCPersons.ToList().FirstOrDefault(x => x.PersonID == (int)Session["userID"]);
                //add these attributes
                if (author != null)
                {
                    gCCrimeReportNote.CRNCrimeID = (int)TempData["passid"];
                    gCCrimeReportNote.CRNAuthorID = author.PersonID;
                    gCCrimeReportNote.CRNDate = DateTime.Now;
                    ////Create the Note
                    //GCCrimeReportNote newNote = new GCCrimeReportNote()
                    //{
                    //    CRNCrimeID = cR.CrimeReportID,
                    //    CRNAuthorID = author.PersonID,
                    //    CRNDate = DateTime.Now,
                    //    CRNote = note
                    //};
                    db.GCCrimeReportNotes.Add(gCCrimeReportNote);
                    db.SaveChanges();
                }

                //db.GCCrimeReportNotes.Add(gCCrimeReportNote);
                //db.SaveChanges();
                //return RedirectToAction("Index");
            }

            ViewBag.CRNCrimeID = new SelectList(db.GCCrimeReports, "CrimeReportID", "Evidence", gCCrimeReportNote.CRNCrimeID);
            ViewBag.CRNAuthorID = new SelectList(db.GCPersons, "PersonID", "PersonFName", gCCrimeReportNote.CRNAuthorID);
            return PartialView(gCCrimeReportNote);
        }

        // GET: GCCrimeReportNotes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCCrimeReportNote gCCrimeReportNote = db.GCCrimeReportNotes.Find(id);
            if (gCCrimeReportNote == null)
            {
                return HttpNotFound();
            }
            ViewBag.CRNCrimeID = new SelectList(db.GCCrimeReports, "CrimeReportID", "Evidence", gCCrimeReportNote.CRNCrimeID);
            ViewBag.CRNAuthorID = new SelectList(db.GCPersons, "PersonID", "PersonFName", gCCrimeReportNote.CRNAuthorID);
            return View(gCCrimeReportNote);
        }

        // POST: GCCrimeReportNotes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CrimeReportNoteID,CRNAuthorID,CRNote,CRNCrimeID,CRNDate")] GCCrimeReportNote gCCrimeReportNote)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gCCrimeReportNote).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CRNCrimeID = new SelectList(db.GCCrimeReports, "CrimeReportID", "Evidence", gCCrimeReportNote.CRNCrimeID);
            ViewBag.CRNAuthorID = new SelectList(db.GCPersons, "PersonID", "PersonFName", gCCrimeReportNote.CRNAuthorID);
            return View(gCCrimeReportNote);
        }

        // GET: GCCrimeReportNotes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCCrimeReportNote gCCrimeReportNote = db.GCCrimeReportNotes.Find(id);
            if (gCCrimeReportNote == null)
            {
                return HttpNotFound();
            }
            return View(gCCrimeReportNote);
        }

        // POST: GCCrimeReportNotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GCCrimeReportNote gCCrimeReportNote = db.GCCrimeReportNotes.Find(id);
            db.GCCrimeReportNotes.Remove(gCCrimeReportNote);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GothamCrimeProject/GothamCrime.UI/Controllers/GCCrimeReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GothamCrimProject.DATA;
using Microsoft.AspNet.Identity;

namespace GothamCrime.UI.Controllers
{
    [Authorize]
    public class GCCrimeReportsController : Controller
    {
        private GothamCrimesEntities db = new GothamCrimesEntities();

        // GET: GCCrimeReports
        public ActionResult Index()
        {
            var gCCrimeReports = db.GCCrimeReports.Include(g => g.GCCrimeReportStatu).Include(g => g.GCLocation).Include(g => g.GCPerson).Include(g => g.GCPerson1);
            return View(gCCrimeReports.ToList());
        }

        // GET: GCCrimeReports/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCCrimeReport gCCrimeReport = db.GCCrimeReports.Find(id);
            if (gCCrimeReport == null)
            {
                return HttpNotFound();
            }
            return View(gCCrimeReport);
        }

        // GET: GCCrimeReports/Create
        public ActionResult Create()
        {
            ViewBag.CrimeReportStatusID = new SelectList(db.GCCrimeReportStatus, "CrimeStatusID", "CrimeStatus");
            ViewBag.CrimeLocationID = new SelectList(db.GCLocations, "LocationID", "LocationZoneName");
            ViewBag.CrimeReporterID = new SelectList(db.GCPersons, "PersonID", "AliasOr");
            ViewBag.CrimeFighterID = new SelectList(db.GCPersons, "PersonID", "AliasOr");
            ViewBag.CrimeSuspectID = new SelectList(db.GCPersons.OrderBy(y => y.TrustRating), "PersonID", "AliasOr");
            return View();
        }

        // POST: GCCrimeReports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CrimeReportID,CrimeReporterID,CrimeFighterID,CrimeSuspectID,Evidence,CrimeLocationID,CrimeDescription,CrimeTimeSubmission,CrimeTimeResolved,CrimeReportStatusID")] GCCrimeReport gCCrimeReport,HttpPostedFileBase evidencePhoto)//String[] selectedRoles
        {
            if (ModelState.IsValid)
            {
                #region Default Values For Crime Report

                //We need to Default the Reporter of the Crime as the user:
                int userID = (int)Session["userID"];
                //For now default to Batman
                gCCrimeReport.CrimeReporterID = userID;

                //Default the Assignment to Batman:
                gCCrimeReport.CrimeFighterID = 10;

                //Default the Submission date to the current date
                gCCrimeReport.CrimeTimeSubmission = DateTime.Now;

                //Default the Status to Pending:
                gCCrimeReport.CrimeReportStatusID = 1;

                #endregion

                #region Evidence Upload
                //Not using a default photo here so leave imgName blank if no evidence
                string imgName = "";
                if (evidencePhoto != null)
                {
                    //Get the file Name from the submission
                    imgName = evidencePhoto.FileName;

                    //Take off the extension to verify filetype
                    string ext = imgName.Substring(imgName.LastIndexOf('.'));

                    //Acceptable extensions:
                    string[] goodExts = new string[] { ".png", ".jpg", ".jpeg", ".gif" };

                    //test
                    if (goodExts.Contains(ext))
                    {
                        //rename the file to protect against duplicates
                        imgName = Guid.NewGuid() + ext;

                        //save to webserver
                        evidencePhoto.SaveAs(Server.MapPath("~/Content/img/EvidenceImages/" + imgName));

                    }else
                    {
                        //Extension no good
                        imgName = "";
                    }//test ext
                }//if evidence is not null

                gCCrimeReport.Evidence = imgName;
                
                #endregion


                db.GCCrimeReports.Add(gCCrimeReport);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CrimeReportStatusID = new SelectList(db.GCCrimeReportStatus, "CrimeStatusID", "CrimeStatus", gCCrimeReport.CrimeReportStatusID);
            ViewBag.CrimeLocationID = new SelectList(db.GCLocations, "LocationID", "LocationZoneName", gCCrimeReport.CrimeLocationID);
            ViewBag.CrimeReporterID = new SelectList(db.GCPersons, "PersonID", "AliasOr", gCCrimeReport.CrimeReporterID);
            ViewBag.CrimeFighterID = new SelectList(db.GCPersons, "PersonID", "AliasOr", gCCrimeReport.CrimeFighterID);
            ViewBag.CrimeSuspectID = new SelectList(db.GCPersons, "PersonID", "AliasOr", gCCrimeReport.CrimeSuspectID);
            return View(gCCrimeReport);
        }

        // GET: GCCrimeReports/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCCrimeReport gCCrimeReport = db.GCCrimeReports.Find(id);
            if (gCCrimeReport == null)
            {
                return HttpNotFound();
            }
            ViewBag.CrimeReportStatusID = new SelectList(db.GCCrimeReportStatus, "CrimeStatusID", "CrimeStatus", gCCrimeReport.CrimeReportStatusID);
            ViewBag.CrimeLocationID = new SelectList(db.GCLocations, "LocationID", "LocationZoneName", gCCrimeReport.CrimeLocationID);
            ViewBag.CrimeReporterID = new SelectList(db.GCPersons, "PersonID", "AliasOr", gCCrimeReport.CrimeReporterID);
            ViewBag.CrimeFighterID = new SelectList(db.GCPersons.AsQueryable().Where(x => x.AffiliationID == 3 || x.AffiliationID == 5).OrderByDescending(y => y.TrustRating), "PersonID", "AliasOr", gCCrimeReport.CrimeFighterID);
            ViewBag.CrimeSuspectID = new SelectList(db.GCPersons, "PersonID", "AliasOr", gCCrimeReport.CrimeSuspectID);
            return View(gCCrimeReport);
        }

        // POST: GCCrimeReports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "CrimeReportID,CrimeReporterID,CrimeFighterID,CrimeSuspectID,Evidence,CrimeLocationID,CrimeDescription,CrimeTimeSubmission,CrimeTimeResolved,CrimeReportStatusID")] GCCrimeReport gCCrimeReport)
        {
            if (ModelState.IsValid)
            {
                gCCrimeReport.CrimeReporterID = gCCrimeReport.CrimeReporterID;
                //Change the date resolved if that status is changed to "Resolved"
                if (gCCrimeReport.CrimeReportStatusID == 3)
                {
                    gCCrimeReport.CrimeTimeResolved = DateTime.Now;
                }
                else if (gCCrimeReport.CrimeReportStatusID != 3)
                {
                    gCCrimeReport.CrimeTimeResolved = null;
                }

                db.Entry(gCCrimeReport).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CrimeReportStatusID = new SelectList(db.GCCrimeReportStatus, "CrimeStatusID", "CrimeStatus", gCCrimeReport.CrimeReportStatusID);
            ViewBag.CrimeLocationID = new SelectList(db.GCLocations, "LocationID", "LocationZoneName", gCCrimeReport.CrimeLocationID);
            ViewBag.CrimeReporterID = new SelectList(db.GCPersons, "PersonID", "AliasOr", gCCrimeReport.CrimeReporterID);
            ViewBag.CrimeFighterID = new SelectList(db.GCPersons, "PersonID", "AliasOr", gCCrimeReport.CrimeFighterID);
            ViewBag.CrimeSuspectID = new SelectList(db.GCPersons, "PersonID", "AliasOr", gCCrimeReport.CrimeSuspectID);
            return View(gCCrimeReport);
        }

        // GET: GCCrimeReports/Delete/5
        [Authorize(Roles = "Bat-min,Ally")]// Need changed to Soft Delete
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCCrimeReport gCCrimeReport = db.GCCrimeReports.Find(id);
            if (gCCrimeReport == null)
            {
                return HttpNotFound();
            }
            return View(gCCrimeReport);
        }

        // POST: GCCrimeReports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Bat-min,Ally")]
        public ActionResult DeleteConfirmed(int id)
        {
            GCCrimeReport gCCrimeReport = db.GCCrimeReports.Find(id);
            #region Soft Delete
            //Change the status of the Crime Report when the delete button is pressed
            if (gCCrimeReport.CrimeReportStatusID != 3)
            {
                //If the Investigation has gone cold
                gCCrimeReport.CrimeReportStatusID = 4;
            }
            #endregion
            //db.GCCrimeReports.Remove(gCCrimeReport);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GothamCrimeProject/GothamCrime.UI/Views/GCCrimeReports/Create.cshtml
@model GothamCrimProject.DATA.GCCrimeReport

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm("Create","GCCrimeReports",FormMethod.Post,new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GCCrimeReport</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
    @*      **Need to Declare this By User
            <div class="form-group">
            @Html.LabelFor(model => model.CrimeReporterID, "CrimeReporterID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CrimeReporterID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CrimeReporterID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.CrimeFighterID, "CrimeFighterID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CrimeFighterID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CrimeFighterID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <label class="control-label col-md-2">Suspect</label>
            <div class="col-md-10">
                @Html.DropDownList("CrimeSuspectID", null, "---Select a Suspect---", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CrimeSuspectID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
                <label class="control-label col-md-2">Evidence</label>
            <div class="col-md-10">
                @*  Don't need default evidence, just leave empty if none                   *@
                @* File Upload for Person Photo *@
                @* Needs to match the parameters accepted in Create Post Action *@
                <input type="file" name="evidencePhoto" />
                @*@Html.ValidationMessageFor(model => model.Evidence, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @* Display the Default Location From User *@
            <label class="control-label col-md-2">Location of Crime</label>
            <div class="col-md-10">
                @Html.DropDownList("CrimeLocationID", null,"---Select Location--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CrimeLocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CrimeDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CrimeDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CrimeDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        @* **Need To Default Time Upon Creation
        <div class="form-group">
        @Html.LabelFor(model => model.CrimeTimeSubmission, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CrimeTimeSubmission, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CrimeTimeSubmission, "", new { @class = "text-danger" })
        </div>
    </div>
            **Default Status Upon Creation
    <div class="form-group">
        @Html.LabelFor(model => model.CrimeReportStatusID, "CrimeReportStatusID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CrimeReportStatusID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CrimeReportStatusID, "", new { @class = "text-danger" })
        </div>
    </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GothamCrimeProject/GothamCrime.UI/Views/GCCrimeReports/Delete.cshtml
@model GothamCrimProject.DATA.GCCrimeReport

@{
    ViewBag.Title = "Delete";
}


<h3>Are you sure you want to declare this investigation as Cold?</h3>
<div class="col-md-10 col-md-push-3">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CrimeTimeSubmission)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CrimeTimeSubmission)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CrimeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CrimeDescription)
        </dd>

        <dt>
            Current Status:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GCCrimeReportStatu.CrimeStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GCLocation.LocationZoneName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GCLocation.LocationZoneName)
        </dd>

        <dt>
            Reported By:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GCPerson.PersonFName)
        </dd>

        <dt>
            Reported Suspect:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GCPerson1.PersonFName)
        </dd>

        <dt>
            Investigation assigned to:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GCPerson2.PersonFName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Gone Cold" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GothamCrimeProject/GothamCrime.UI/Views/GCCrimeReports/Details.cshtml
@model GothamCrimProject.DATA.GCCrimeReport

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        @if (Request.IsAuthenticated && (!User.IsInRole("Citizen") || (int)Session["userID"] == Model.CrimeReporterID))
        {
            <dt>
                @Html.DisplayNameFor(model => model.Evidence)
            </dt>

            <dd>
                @if (Model.Evidence != null)
                {
                    <img src="@Url.Content("~/Content/img/EvidenceImages/" + Model.Evidence)" />
                }
                else
                {
                    <h3>No Evidence Submitted</h3>
                }

            </dd>

        }
        <dt>
            @Html.DisplayNameFor(model => model.CrimeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CrimeDescription)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.GCCrimeReportStatu.CrimeStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GCCrimeReportStatu.CrimeStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GCLocation.LocationZoneName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GCLocation.LocationZoneName)
        </dd>

        <dt>
            Reported By
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GCPerson.AliasOr)
        </dd>

        <dt>
            Assigned To
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GCPerson1.AliasOr)
        </dd>

        <dt>
            Reported Suspect
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GCPerson2.AliasOr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CrimeTimeSubmission)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CrimeTimeSubmission)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CrimeTimeResolved)
        </dt>

        <dd>
            @if (Model.CrimeTimeResolved == null)
            {
                <p>Not yet resolved</p>
            }
            else
            {
                @Html.DisplayFor(model => model.CrimeTimeResolved)
            }
        </dd>
    </dl>
</div>
<p>
    @*Fix so user can edit their own*@
    @if (Request.IsAuthenticated && (User.IsInRole("Bat-min") || (int)Session["userID"] == Model.CrimeReporterID))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.CrimeReportID }) }|
    @Html.ActionLink("Back to List", "Index")
</p>


<div>
        @foreach (var note in Model.GCCrimeReportNotes.AsQueryable().Where(x => x.CRNCrimeID == Model.CrimeReportID))
        {

            <img id="noteThumb" src="@Url.Content("~/Content/img/PersonImages/" + note.GCPerson.PersonImage)" />
            
                <strong>
                    "@Html.DisplayFor(model => note.CRNote)"
                </strong>
                <i>Posted: @Html.DisplayFor(model => note.CRNDate)</i>
                <br />
                <br />


        } 
           @{Html.RenderAction("Create", "GCCrimeReportNotes", new { id = Model.CrimeReportID });}
  
</div>