GothamCrimeProject/GothamCrime.UI/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GothamCrime.UI.Models
{
    public class ContactViewModel
    {
        [Required(ErrorMessage = "* Required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "* Required")]
        [RegularExpression(@"^[A-Za-z0-9](([_\.\-]?[a-zA-Z0-9]+)*)@([A-Za-z0-9]+)(([\.\-]?[a-zA-Z0-9]+)*)\.([A-Za-z]{2,})$", ErrorMessage = "Please enter a valid email.")] //Checks if email is formatted to a valid email, doesn't confirm email.
        public string Email { get; set; }

        [Required(ErrorMessage = "* Required")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "* Required")]
        [UIHint("MultilineText")]
        public string Message { get; set; }
    }
}

GothamCrimeProject/GothamCrime.UI/Controllers/GCAffiliationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GothamCrimProject.DATA;

namespace GothamCrime.UI.Controllers
{
    [Authorize(Roles ="Bat-min")]
    public class GCAffiliationsController : Controller
    {
        private GothamCrimesEntities db = new GothamCrimesEntities();

        // GET: GCAffiliations
        public ActionResult Index()
        {
            return View(db.GCAffiliations.ToList());
        }

        // GET: GCAffiliations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCAffiliation gCAffiliation = db.GCAffiliations.Find(id);
            if (gCAffiliation == null)
            {
                return HttpNotFound();
            }
            return View(gCAffiliation);
        }

        // GET: GCAffiliations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GCAffiliations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AffiliationID,AffilitationName,AffilitationDescription")] GCAffiliation gCAffiliation)
        {
            if (ModelState.IsValid)
            {
                db.GCAffiliations.Add(gCAffiliation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gCAffiliation);
        }

        // GET: GCAffiliations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCAffiliation gCAffiliation = db.GCAffiliations.Find(id);
            if (gCAffiliation == null)
            {
                return HttpNotFound();
            }
            return View(gCAffiliation);
        }

        // POST: GCAffiliations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AffiliationID,AffilitationName,AffilitationDescription")] GCAffiliation gCAffiliation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gCAffiliation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gCAffiliation);
        }

        // GET: GCAffiliations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCAffiliation gCAffiliation = db.GCAffiliations.Find(id);
            if (gCAffiliation == null)
            {
                return HttpNotFound();
            }
            return View(gCAffiliation);
        }

        // POST: GCAffiliations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GCAffiliation gCAffiliation = db.GCAffiliations.Find(id);
            db.GCAffiliations.Remove(gCAffiliation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GothamCrimeProject/GothamCrime.UI/Controllers/GCPersonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GothamCrimProject.DATA;
using Microsoft.AspNet.Identity.Owin;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;

namespace GothamCrime.UI.Controllers
{
    [Authorize]
    public class GCPersonsController : Controller
    {
        private GothamCrimesEntities db = new GothamCrimesEntities();

        // GET: GCPersons
        [Authorize(Roles = "Bat-min,Ally,Law Enforcement")]
        public ActionResult Index()
        {
            var gCPersons = db.GCPersons.Include(g => g.GCAffiliation).Include(g => g.GCLocation).Include(g => g.GCPersonStatu);
            return View(gCPersons.ToList());
        }

        // GET: GCPersons/Details/5
        [Authorize(Roles = "Bat-min,Ally,Law Enforcement")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCPerson gCPerson = db.GCPersons.Find(id);
            if (gCPerson == null)
            {
                return HttpNotFound();
            }
            return View(gCPerson);
        }

        // GET: GCPersons/Create
        [Authorize(Roles = "Bat-min")]
        public ActionResult Create()
        {
            ViewBag.AffiliationID = new SelectList(db.GCAffiliations, "AffiliationID", "AffilitationName");
            ViewBag.PersonLocationID = new SelectList(db.GCLocations, "LocationID", "LocationZoneName");
            ViewBag.PersonStatusID = new SelectList(db.GCPersonStatus, "PersonStatusID", "PersonStatusName");
            return View();
        }

        // POST: GCPersons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Bat-min")]
        public ActionResult Create([Bind(Include = "PersonID,PersonFName,PersonLName,PersonAlias,ContactPhone,PersonLocationID,AffiliationID,Occupation,PersonStatusID,PersonNotableFeatures,TrustRating,PersonImage")] GCPerson gCPerson, HttpPostedFileBase personPhoto)//string[] selected roles
        {
            if (ModelState.IsValid)
            {
                //Having all people be created by Batman so no default information
                //This keeps the integrity of the system

                #region Generate a default login
                //Don't need to make a login for Villains

                if (gCPerson.AffiliationID != 1 && gCPerson.PersonStatusID == 1)
                {
                    gCPerson.PersonEmail = (gCPerson.PersonAlias != null ? gCPerson.PersonAlias.ToString() : gCPerson.PersonFName.Substring(0, 1).ToLower() + gCPerson.PersonLName.ToString()) + "@GothamBC.com";
                    //User Manager
                    var userManager = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>();
                    //create app user
                    var newUser = new ApplicationUser()
                    {
                        UserName = (gCPerson.PersonAlias != null ? gCPerson.PersonAlias.ToString() : gCPerson.PersonFName.Substring(0, 1).ToLower() + gCPerson.PersonLName.ToString()),
                        Email = gCPerson.PersonEmail
                    };

                    var chkUser = userManager.Create(newUser, newUser.UserName + "B@4u");

                    //This Will check to see if the Create works, since I ran into errors with this
                    if (chkUser.Succeeded)
                    {
                        userManager.AddToRole(newUser.Id, "Citizen");
                    }
                }

                #endregion

                #region Enable File Upload
                //Make sure to have default photo
                //default imgName
                string imgName = "defaultPhoto.jpg";

                if (personPhoto != null)
                {
                    //take the file name
                    imgName = personPhoto.FileName;

                    //Check extension
                    //take off ext
                    string ext = imgName.Substring(imgName.LastIndexOf('.'));

                    //Compare against good exts
                    string[] goodExts = new string[] { ".png", ".jpg", ".jpeg", ".gif" };

                    if (goodExts.Contains(ext))
                    {
                        //Rename File
                        imgName = Guid.NewGuid() + ext;

                        //Save file
                        personPhoto.SaveAs(Server.MapPath("~/Content/img/PersonImages/" + imgName));

                    }
                    else
                    {
                        imgName = "defaultPhoto.jpg";
                    }//end ext check
                }//end photo capture
                //assign persons image
                gCPerson.PersonImage = imgName;


                #endregion

                db.GCPersons.Add(gCPerson);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AffiliationID = new SelectList(db.GCAffiliations, "AffiliationID", "AffilitationName", gCPerson.AffiliationID);
            ViewBag.PersonLocationID = new SelectList(db.GCLocations, "LocationID", "LocationZoneName", gCPerson.PersonLocationID);
            ViewBag.PersonStatusID = new SelectList(db.GCPersonStatus, "PersonStatusID", "PersonStatusName", gCPerson.PersonStatusID);
            return View(gCPerson);
        }

        // GET: GCPersons/Edit/5
        [Authorize(Roles = "Bat-min")]
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCPerson gCPerson = db.GCPersons.Find(id);
            if (gCPerson == null)
            {
                return HttpNotFound();
            }
            ViewBag.AffiliationID = new SelectList(db.GCAffiliations, "AffiliationID", "AffilitationName", gCPerson.AffiliationID);
            ViewBag.PersonLocationID = new SelectList(db.GCLocations, "LocationID", "LocationZoneName", gCPerson.PersonLocationID);
            ViewBag.PersonStatusID = new SelectList(db.GCPersonStatus, "PersonStatusID", "PersonStatusName", gCPerson.PersonStatusID);
            return View(gCPerson);
        }

        // POST: GCPersons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Bat-min")]
        public ActionResult Edit([Bind(Include = "PersonID,PersonFName,PersonLName,PersonAlias,ContactPhone,PersonLocationID,AffiliationID,Occupation,PersonStatusID,PersonNotableFeatures,TrustRating,PersonImage")] GCPerson gCPerson, HttpPostedFileBase personPhoto)//string[] selected roles
        {
            if (ModelState.IsValid)
            {
                #region Enable File Upload
                //Make sure to have default photo
                //Image will already have something in it here.

                if (personPhoto != null)
                {
                    //take the file name
                    string imgName = personPhoto.FileName;

                    //Check extension
                    //take off ext
                    string ext = imgName.Substring(imgName.LastIndexOf('.'));

                    //Compare against good exts
                    string[] goodExts = new string[] { ".png", ".jpg", ".jpeg", ".gif" };

                    if (goodExts.Contains(ext))
                    {
                        //Rename File
                        imgName = Guid.NewGuid() + ext;

                        //Save file
                        personPhoto.SaveAs(Server.MapPath("~/Content/img/PersonImages/" + imgName));

                        gCPerson.PersonImage = imgName;
                    }
                }//end photo capture
                 //Hidden Field will hold original



                #endregion

                //#region Fix the Current Data
                //if (gCPerson.AffiliationID != 1 && gCPerson.PersonStatusID == 1)
                //{
                //    gCPerson.PersonEmail = (gCPerson.PersonAlias != null ? gCPerson.PersonAlias.ToString() : gCPerson.PersonFName.Substring(0, 1).ToLower() + gCPerson.PersonLName.ToString()) + "@GothamBC.com";
                //    //User Manager
                //    var userManager = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>();
                //    //create app user
                //    var newUser = new ApplicationUser()
                //    {
                //        UserName = (gCPerson.PersonAlias != null ? gCPerson.PersonAlias.ToString() : gCPerson.PersonFName.Substring(0, 1).ToLower() + gCPerson.PersonLName.ToString() + "@GothamBC.com"),
                //        Email = gCPerson.PersonEmail
                //    };

                //    var chkUser = userManager.Create(newUser, newUser.UserName + "B@4u");

                //    //newUser.Id = gCPerson.PersonID.ToString();
                //    //newUser.PhoneNumber = gCPerson.ContactPhone;
                //    if (chkUser.Succeeded)
                //    {
                //    userManager.AddToRole(newUser.Id, "Citizen");
                //    }
                //}
                //#endregion

                db.Entry(gCPerson).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

GothamCrimeProject/GothamCrime.UI/Controllers/HomeController.cs
using GothamCrime.UI.Models;
using System;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;

namespace IdentitySample.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult About()
        {

            return View();
        }

        public ActionResult Contact()
        {

            return View();
        }
        public ActionResult BatminFunc()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Contact(ContactViewModel contact)
        {
            if (ModelState.IsValid)
            {


                //Process contact form and send an email

                //create body of email
                string body = string.Format("Name: {0}<br/>Email: {1}<br/>Subject: {2}<br/>Message: {3}",
                        contact.Name, contact.Name, contact.Subject, contact.Message);

                //Create and configure mail message

                MailMessage msg = new MailMessage("no-reply@nickmcsimpson.com", "n.mcsimp@gmail.com", "Contact From Final Project" + contact.Subject, body);
                msg.IsBodyHtml = true;
                msg.Priority = MailPriority.High;

                //Configure SMTP client
                SmtpClient client = new SmtpClient("mail.nickmcsimpson.com");
                client.Credentials = new NetworkCredential("no-reply@nickmcsimpson.com", "l@M2afmwba");

                using (client)
                {
                    try
                    {
                        client.Send(msg);
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Fail = ex.StackTrace;
                        ViewBag.ErrorMessage = "There was an error sending your email, please try again.";
                        return View();
                    }
                }//end email send

                //send to confirmation page
                return View("ContactConfirmation", contact);
            }//end if ModelState
            //Otherwise
            return View(contact);

        }//end Contact post


    }
}

GothamCrimeProject/GothamCrime.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<hgroup>
    <h2>@ViewBag.Title</h2>
</hgroup>
<div class="col-md-10 col-md-push-1">

       
        <div class="col-md-10 col-md-push-1">
            <img src="~/Content/img/Batman75_Logo_v2_2.png" />
            <h3 class="text-center">Origins</h3>
            <p>"The Worlds Greatest Detective" does a lot for the city of Gotham, but one man can't stop all the crime in this huge city. 
            The biggest advancement in Bat-tech since the Bat symbol itself. Gotham Crimes is the beacon of light for all. Gotham's history is
            dominated by organized crime and corruption, but with the unveiling of this collective crime prevention network, everyone is able to contribute to 
            the protection of the city. The average citizen is no longer silenced by the likes of the Joker or the Falcone's and everyone is held responsible for the good of the city.
            </p>
            <a href="~/Content/NicholasMcSimpDocumentation.pdf">Documentation</a>
        </div>
</div>

GothamCrimeProject/GothamCrime.UI/Views/Home/BatminFunc.cshtml
@{
    ViewBag.Title = "BatminFunc";
}

<h2>Bat-min</h2>
@*<li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
<li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")
<li>@Html.ActionLink("Affiliations", "Index", "GCAffiliations")
<li>@Html.ActionLink("PersonStatus", "Index", "GCPersonStatus")
<li>@Html.ActionLink("Crime Report Status", "Index", "GCCrimeReportStatus")
<li>@Html.ActionLink("Persons", "Index", "GCPersons")                       *@
    <h3 class="text-center">Admin Functions</h3>
<ul>
    <li class="btn btn-default btn-block">@Html.ActionLink("Roles Manager", "Index", "RolesAdmin")</li>
    <li class="btn btn-default btn-block">@Html.ActionLink("Users Manager", "Index", "UsersAdmin")</li>
</ul>
<h3 class="text-center">Manage Database Tables</h3>
<ul>
    <li class="btn btn-default btn-block">@Html.ActionLink("Gotham Residents", "Index", "GCPersons")</li>
    <li class="btn btn-default btn-block">@Html.ActionLink("Person Affiliations", "Index", "GCAffiliations")</li>
    <li class="btn btn-default btn-block">@Html.ActionLink("Person Status", "Index", "GCPersonStatus")</li>
    <li class="btn btn-default btn-block">@Html.ActionLink("Crime Report Status", "Index", "GCCrimeReportStatus")</li>
</ul>

GothamCrimeProject/GothamCrime.UI/Views/Home/Contact.cshtml
@model GothamCrime.UI.Models.ContactViewModel
@{
    ViewBag.Title = "Contact";
}

<h2>Contact</h2>
<p class="text-danger">Please note this will not be sent to Batman, but to the creator of this project: Nicholas McClain-Simpson</p>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<h5 style="color:red;">@ViewBag.Fail</h5>*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

GothamCrimeProject/GothamCrime.UI/Views/Home/ContactConfirmation.cshtml
@{
    ViewBag.Title = "ContactConfirmation";
}

<h2>ContactConfirmation</h2>

<div class="col-sm-8 col-sm-push-2">
    <h3>Your Email Has Been Sent</h3>
    <div>
        <p>Thank you, @Model.Name for contacting me!</p>

        <h4>Your Email:</h4>
        <h5>Subject:</h5>
        <p>@Model.Subject</p>
        <h5>Message:</h5>
        <p>@Model.Message</p>
        <h5>A reply will be sent to:</h5>
        <p>@Model.Email</p>
    </div>
    <a class="btn btn-default btn-block" href="@Url.Action("Index","Home")" title="Home">Home</a>
</div>

GothamCrimeProject/GothamCrime.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Gotham Crimes</h1>
    <p class="lead">"<i>How does one man protect an entire city? By making sure the shadow he casts is long and wide... So that its reach can embrace - or engulf - all that walk here. So that every man, woman and child in the city of Gotham can feel its touch. If you are good, the shadow's wings are a welcome, protective blanket. If you are bad, you know its touch as a black  splinter of fear.</i>" - <strong>Batman</strong></p>

    <div class="row">
        @if (@Session["personName"] != null)
        {
            <h3 class="text-center">Welcome back, @Session["personName"]</h3>
        }

        @if (@Session["userPhoto"] != null)
        {
            <div class="col-md-8 col-md-push-2">
            <img class="personPhoto" src="~/Content/img/PersonImages/@Session["userPhoto"]" alt="Image for @Session["personName"]" />

        </div>
        }


        </div>

        <div class="clearfix">
            <br />
            <br />
            <br />
        </div>
        <p class="btn btn-default btn-block">@Html.ActionLink("Report a Crime", "Create", "GCCrimeReports")</p>
    </div>