GothamCrimeProject/GothamCrime.UI/Controllers/GCLocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GothamCrimProject.DATA;

namespace GothamCrime.UI.Controllers
{
    [Authorize]
    public class GCLocationsController : Controller
    {
        private GothamCrimesEntities db = new GothamCrimesEntities();

        // GET: GCLocations
        public ActionResult Index()
        {
            return View(db.GCLocations.ToList());
        }

        // GET: GCLocations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCLocation gCLocation = db.GCLocations.Find(id);
            if (gCLocation == null)
            {
                return HttpNotFound();
            }
            return View(gCLocation);
        }

        // GET: GCLocations/Create
        [Authorize(Roles = "Bat-min")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: GCLocations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Bat-min")]
        public ActionResult Create([Bind(Include = "LocationID,LocationZoneName,LocationZoneDescription")] GCLocation gCLocation)
        {
            if (ModelState.IsValid)
            {
                db.GCLocations.Add(gCLocation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gCLocation);
        }

        // GET: GCLocations/Edit/5
        [Authorize(Roles = "Bat-min")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCLocation gCLocation = db.GCLocations.Find(id);
            if (gCLocation == null)
            {
                return HttpNotFound();
            }
            return View(gCLocation);
        }

        // POST: GCLocations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Bat-min")]
        public ActionResult Edit([Bind(Include = "LocationID,LocationZoneName,LocationZoneDescription")] GCLocation gCLocation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gCLocation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gCLocation);
        }

        // GET: GCLocations/Delete/5
        [Authorize(Roles = "Bat-min")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCLocation gCLocation = db.GCLocations.Find(id);
            if (gCLocation == null)
            {
                return HttpNotFound();
            }
            return View(gCLocation);
        }

        // POST: GCLocations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Bat-min")]
        public ActionResult DeleteConfirmed(int id)
        {
            GCLocation gCLocation = db.GCLocations.Find(id);
            db.GCLocations.Remove(gCLocation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GothamCrimeProject/GothamCrime.UI/Controllers/GCPersonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GothamCrimProject.DATA;
using Microsoft.AspNet.Identity.Owin;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;

namespace GothamCrime.UI.Controllers
{
    [Authorize]
    public class GCPersonsController : Controller
    {
        private GothamCrimesEntities db = new GothamCrimesEntities();

        // GET: GCPersons
        [Authorize(Roles = "Bat-min,Ally,Law Enforcement")]
        public ActionResult Index()
        {
            var gCPersons = db.GCPersons.Include(g => g.GCAffiliation).Include(g => g.GCLocation).Include(g => g.GCPersonStatu);
            return View(gCPersons.ToList());
        }

        // GET: GCPersons/Details/5
        [Authorize(Roles = "Bat-min,Ally,Law Enforcement")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCPerson gCPerson = db.GCPersons.Find(id);
            if (gCPerson == null)
            {
                return HttpNotFound();
            }
            return View(gCPerson);
        }

        // GET: GCPersons/Create
        [Authorize(Roles = "Bat-min")]
        public ActionResult Create()
        {
            ViewBag.AffiliationID = new SelectList(db.GCAffiliations, "AffiliationID", "AffilitationName");
            ViewBag.PersonLocationID = new SelectList(db.GCLocations, "LocationID", "LocationZoneName");
            ViewBag.PersonStatusID = new SelectList(db.GCPersonStatus, "PersonStatusID", "PersonStatusName");
            return View();
        }

        // POST: GCPersons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Bat-min")]
        public ActionResult Create([Bind(Include = "PersonID,PersonFName,PersonLName,PersonAlias,ContactPhone,PersonLocationID,AffiliationID,Occupation,PersonStatusID,PersonNotableFeatures,TrustRating,PersonImage")] GCPerson gCPerson, HttpPostedFileBase personPhoto)//string[] selected roles
        {
            if (ModelState.IsValid)
            {
                //Having all people be created by Batman so no default information
                //This keeps the integrity of the system

                #region Generate a default login
                //Don't need to make a login for Villains

                if (gCPerson.AffiliationID != 1 && gCPerson.PersonStatusID == 1)
                {
                    gCPerson.PersonEmail = (gCPerson.PersonAlias != null ? gCPerson.PersonAlias.ToString() : gCPerson.PersonFName.Substring(0, 1).ToLower() + gCPerson.PersonLName.ToString()) + "@GothamBC.com";
                    //User Manager
                    var userManager = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>();
                    //create app user
                    var newUser = new ApplicationUser()
                    {
                        UserName = (gCPerson.PersonAlias != null ? gCPerson.PersonAlias.ToString() : gCPerson.PersonFName.Substring(0, 1).ToLower() + gCPerson.PersonLName.ToString()),
                        Email = gCPerson.PersonEmail
                    };

                    var chkUser = userManager.Create(newUser, newUser.UserName + "B@4u");

                    //This Will check to see if the Create works, since I ran into errors with this
                    if (chkUser.Succeeded)
                    {
                        userManager.AddToRole(newUser.Id, "Citizen");
                    }
                }

                #endregion

                #region Enable File Upload
                //Make sure to have default photo
                //default imgName
                string imgName = "defaultPhoto.jpg";

                if (personPhoto != null)
                {
                    //take the file name
                    imgName = personPhoto.FileName;

                    //Check extension
                    //take off ext
                    string ext = imgName.Substring(imgName.LastIndexOf('.'));

                    //Compare against good exts
                    string[] goodExts = new string[] { ".png", ".jpg", ".jpeg", ".gif" };

                    if (goodExts.Contains(ext))
                    {
                        //Rename File
                        imgName = Guid.NewGuid() + ext;

                        //Save file
                        personPhoto.SaveAs(Server.MapPath("~/Content/img/PersonImages/" + imgName));

                    }
                    else
                    {
                        imgName = "defaultPhoto.jpg";
                    }//end ext check
                }//end photo capture
                //assign persons image
                gCPerson.PersonImage = imgName;


                #endregion

                db.GCPersons.Add(gCPerson);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AffiliationID = new SelectList(db.GCAffiliations, "AffiliationID", "AffilitationName", gCPerson.AffiliationID);
            ViewBag.PersonLocationID = new SelectList(db.GCLocations, "LocationID", "LocationZoneName", gCPerson.PersonLocationID);
            ViewBag.PersonStatusID = new SelectList(db.GCPersonStatus, "PersonStatusID", "PersonStatusName", gCPerson.PersonStatusID);
            return View(gCPerson);
        }

        // GET: GCPersons/Edit/5
        [Authorize(Roles = "Bat-min")]
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCPerson gCPerson = db.GCPersons.Find(id);
            if (gCPerson == null)
            {
                return HttpNotFound();
            }
            ViewBag.AffiliationID = new SelectList(db.GCAffiliations, "AffiliationID", "AffilitationName", gCPerson.AffiliationID);
            ViewBag.PersonLocationID = new SelectList(db.GCLocations, "LocationID", "LocationZoneName", gCPerson.PersonLocationID);
            ViewBag.PersonStatusID = new SelectList(db.GCPersonStatus, "PersonStatusID", "PersonStatusName", gCPerson.PersonStatusID);
            return View(gCPerson);
        }

        // POST: GCPersons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Bat-min")]
        public ActionResult Edit([Bind(Include = "PersonID,PersonFName,PersonLName,PersonAlias,ContactPhone,PersonLocationID,AffiliationID,Occupation,PersonStatusID,PersonNotableFeatures,TrustRating,PersonImage")] GCPerson gCPerson, HttpPostedFileBase personPhoto)//string[] selected roles
        {
            if (ModelState.IsValid)
            {
                #region Enable File Upload
                //Make sure to have default photo
                //Image will already have something in it here.

                if (personPhoto != null)
                {
                    //take the file name
                    string imgName = personPhoto.FileName;

                    //Check extension
                    //take off ext
                    string ext = imgName.Substring(imgName.LastIndexOf('.'));

                    //Compare against good exts
                    string[] goodExts = new string[] { ".png", ".jpg", ".jpeg", ".gif" };

                    if (goodExts.Contains(ext))
                    {
                        //Rename File
                        imgName = Guid.NewGuid() + ext;

                        //Save file
                        personPhoto.SaveAs(Server.MapPath("~/Content/img/PersonImages/" + imgName));

                        gCPerson.PersonImage = imgName;
                    }
                }//end photo capture
                 //Hidden Field will hold original



                #endregion

                //#region Fix the Current Data
                //if (gCPerson.AffiliationID != 1 && gCPerson.PersonStatusID == 1)
                //{
                //    gCPerson.PersonEmail = (gCPerson.PersonAlias != null ? gCPerson.PersonAlias.ToString() : gCPerson.PersonFName.Substring(0, 1).ToLower() + gCPerson.PersonLName.ToString()) + "@GothamBC.com";
                //    //User Manager
                //    var userManager = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>();
                //    //create app user
                //    var newUser = new ApplicationUser()
                //    {
                //        UserName = (gCPerson.PersonAlias != null ? gCPerson.PersonAlias.ToString() : gCPerson.PersonFName.Substring(0, 1).ToLower() + gCPerson.PersonLName.ToString() + "@GothamBC.com"),
                //        Email = gCPerson.PersonEmail
                //    };

                //    var chkUser = userManager.Create(newUser, newUser.UserName + "B@4u");

                //    //newUser.Id = gCPerson.PersonID.ToString();
                //    //newUser.PhoneNumber = gCPerson.ContactPhone;
                //    if (chkUser.Succeeded)
                //    {
                //    userManager.AddToRole(newUser.Id, "Citizen");
                //    }
                //}
                //#endregion

                db.Entry(gCPerson).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

GothamCrimeProject/GothamCrime.UI/Controllers/NotableCharactersController.cs
using GothamCrimProject.DATA;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace GothamCrime.UI.Controllers
{
    [Authorize]
    public class NotableCharactersController : Controller
    {
        private GothamCrimesEntities db = new GothamCrimesEntities();

        // GET: NotableCharacters
        public ActionResult Index()
        {
            //Here will Show the 3 Links for Villains, Heros, GCPD
            return View();
        }
        //Villains page:
        public ActionResult Villains()
        {
            //Include the data base call from PersonsController
            //Modify it to only show the Villains
            var gCVillains = db.GCPersons.Include(g => g.GCAffiliation).Include(g => g.GCLocation).Include(g => g.GCPersonStatu).AsQueryable().Where(g => g.AffiliationID.ToString() == "1");

            return View(gCVillains.ToList());
        }
        //Villains page:
        public ActionResult GCPD()      //These Will Match the Villains
        {//Include the data base call from PersonsController
            //Modify it to only show the Villains
            var gCLawEnforcement = db.GCPersons.Include(g => g.GCAffiliation).Include(g => g.GCLocation).Include(g => g.GCPersonStatu).AsQueryable().Where(g => g.AffiliationID.ToString() == "5");

            return View(gCLawEnforcement.ToList());
        }
        //Villains page:
        public ActionResult Vigilantes()
        {//Include the data base call from PersonsController
            //Modify it to only show the Villains
            var gCVigilantes = db.GCPersons.Include(g => g.GCAffiliation).Include(g => g.GCLocation).Include(g => g.GCPersonStatu).AsQueryable().Where(g => g.AffiliationID.ToString() == "3");

            return View(gCVigilantes.ToList());
        }
        public ActionResult Details(int? id) //Edit this to make it look Pretty
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GCPerson gCPerson = db.GCPersons.Find(id);
            if (gCPerson == null)
            {
                return HttpNotFound();
            }
            return View(gCPerson);
        }
    }
}

GothamCrimeProject/GothamCrime.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A representation of what a Crime Reporting website for Gotham City could be">
    <meta name="keywords" content="Batman, MVC, HTML, CSS, Bootstrap, Final, Project, Centriq, Web, Developer" />
    <link rel="icon" href="~/Baticon.png">

    <meta name="author" content="Nicholas McClain-Simpson">
    <title>@ViewBag.Title - Gotham Crimes</title>


    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="~/Content/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles -->
    <link href="~/Content/style.css" rel="stylesheet">
    <!-- Color -->
    <link id="skin" href="~/Content/misty.css" rel="stylesheet">

    @*@Styles.Render("~/Content/css")*@
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://use.fontawesome.com/403e0908b1.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.css">


    @* This Application was made for educational purposes only, I don't own any of the Warner Bros content. *@


</head>
<body>
    <!-- Start preloading -->
    <div id="loading" class="loading-invisible">
        <div class="loading-center">
            <div class="loading-center-absolute">
                <div class="object" id="object_one"></div>
                <div class="object" id="object_two"></div>
                <div class="object" id="object_three"></div>
                <div class="object" id="object_four"></div>
                <div class="object" id="object_five"></div>
                <div class="object" id="object_six"></div>
                <div class="object" id="object_seven"></div>
                <div class="object" id="object_eight"></div>
                <div class="object" id="object_big"></div>
            </div>
            <p>Please wait...</p>
        </div>
    </div>
    <script type="text/javascript">
        document.getElementById("loading").className = "loading-visible";
        var hideDiv = function () { document.getElementById("loading").className = "loading-invisible"; };
        var oldLoad = window.onload;
        var newLoad = oldLoad ? function () { hideDiv.call(this); oldLoad.call(this); } : hideDiv;
        window.onload = newLoad;
    </script>
    <!-- End preloading -->
    <div id="offfcavas">
        <!-- Start menu -->
        <div class="menu-wrap">
            <button class="close-button" id="close-button"><i class="fa fa-remove"></i></button>
            <img src="~/Content/img/Batman75_Logo_v2_2.png" class="logo" alt="BatSymbol" style="margin-left: -50px;" />
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("GC Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About Gotham Crimes", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                @if (Request.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Map of Gotham", "Index", "GCLocations")</li>
                    <li>@Html.ActionLink("Crime Reports", "Index", "GCCrimeReports")</li>
                    <li>@Html.ActionLink("Figures Of Gotham", "Index", "NotableCharacters")</li>

                }

                @if (Request.IsAuthenticated && User.IsInRole("Bat-min"))
                {
                    @*<li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                        <li>@Html.ActionLink("Affiliations", "Index", "GCAffiliations")</li>
                        <li>@Html.ActionLink("PersonStatus", "Index", "GCPersonStatus")</li>
                        <li>@Html.ActionLink("Crime Report Status", "Index", "GCCrimeReportStatus")</li>
                        <li>@Html.ActionLink("Persons", "Index", "GCPersons")</li>*@

                    <li>@Html.ActionLink("Bat-min", "BatminFunc", "Home")</li>

                }
                <li>@Html.Partial("_LoginPartial")</li>

            </ul>
            <div class="copyright">2017 &copy; Copyright <a href="http://nickmcsimpson.com/">Nicholas McClain-Simpson</a> All rights Reserved.</div>
        </div>
        <!-- End menu -->
        <!-- Start offcanvas wrapper -->
        <div class="content-wrap">
            <div class="offfcavas-content">
                <div class="menu-bar-wrapp">
                    <button class="menu-bar" id="open-button" type="button"><i class="fa fa-bars"></i></button>
                    <a href="@Url.Action("Index","Home")" class="socila-icon"><i class="fa fa-home"></i></a>
                    <a href="@Url.Action("Index","GCCrimeReports")" class="socila-icon"><i class="fa fa-list-alt"></i></a>
                    <a href="@Url.Action("Index","NotableCharacters")" class="socila-icon"><i class="fa fa-user-secret"></i></a>
                </div>

                <!--Main Body-->
                @if (ViewBag.HideBack == null)
                {
                    <div id="bodyContent">
                        @RenderBody()
                    </div>
                }
                else
                {
                    <div>
                        @RenderBody()
                    </div>
                }
                <!-- End Main Body-->
                <!-- Start portfolio load mor
                <div id="js-loadMore-full-width" class="cbp-l-loadMore-full-width">
                    <a href="portfolioDetail/loadMore-fullwidth-4column.html" class="cbp-l-loadMore-link" rel="nofollow">
                        <span class="cbp-l-loadMore-defaultText">LOAD MORE</span>
                        <span class="cbp-l-loadMore-loadingText">LOADING...</span>
                        <span class="cbp-l-loadMore-noMoreLoading">NO MORE WORKS</span>
                    </a>
                </div>e-->
                <!-- End portfolio load more-->
            </div>
        </div>
        <!-- End offcanvas wrapper -->
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/Content/js/jquery.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/bootsnav.js"></script>
    <script src="~/Content/js/jquery.easing-1.3.min.js"></script>

    <script src="~/Content/js/ie10-viewport-bug-workaround.js"></script>


    <script src="~/Content/js/form/jcf.js"></script>
    <script src="~/Content/js/form/jcf.scrollable.js"></script>
    <script src="~/Content/js/form/jcf.select.js"></script>


    @*<script src="~/Content/js/checkator/fm.checkator.jquery.js"></script>
        <script src="~/Content/js/checkator/setting.js"></script>*@


    <script src="~/Content/js/custominput/modernizr.js"></script>
    <script src="~/Content/js/custominput/custom-file-input.js"></script>

    <!-- offcanvas -->
    <script src="~/Content/js/offcanvas/classie.js"></script>
    <script src="~/Content/js/offcanvas/setting.js"></script>


    <script src="~/Content/js/cubeportfolio/jquery.cubeportfolio.min.js"></script>
    <script src="~/Content/js/cubeportfolio/masonry.js"></script>

    <script src="~/Content/js/typer/jquery.typer.js"></script>
    <script src="~/Content/js/typer/setting.js"></script>

    <script src="~/Content/js/parallax/jquery.parallax-1.1.3.js"></script>
    <script src="~/Content/js/parallax/setting.js"></script>

    <script src="~/Content/js/custom.js"></script>

    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.js"></script>

</body>
</html>
@RenderSection("scripts", false)